name: Textão
description: Prometo não invocar Cthulhu - Meu português é horrível, me perdoe.
meta_description: "Prometo não invocar Cthulhu"

aboutPage: true

gems: ["jekyll-paginate"]

markdown: redcarpet
redcarpet:
  extensions: ["strikethrough", "superscript"]

# highlighter: pygments

paginate: 20
baseurl: /textao/
domain_name: 'http://textao.ues.li/'
# google_analytics: 'UA-XXXXXXXX-X'
# disqus: false
# disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://textao.ues.li/'
author:         'Wesley Schleumer de Góes'
authorTwitter:  'schleumer'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

exclude: ['vendor', '.git/', 'Gemfile', 'Gemfile.lock']
